//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kyrsachVPKS.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITschoolEntities : DbContext
    {
        public ITschoolEntities()
            : base("name=ITschoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<Administrators> Administrators { get; set; }
        public virtual DbSet<Courses> Courses { get; set; }
        public virtual DbSet<Documents> Documents { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<Guardians> Guardians { get; set; }
        public virtual DbSet<RegistrationAddress> RegistrationAddress { get; set; }
        public virtual DbSet<Requests> Requests { get; set; }
        public virtual DbSet<ResidenceAddress> ResidenceAddress { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Teachers> Teachers { get; set; }
    }
}
