//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kyrsachVPKS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public long ID { get; set; }
        public string Status { get; set; }
        public string Contract { get; set; }
        public System.DateTime Date_of_creation { get; set; }
        public long ID_Students { get; set; }
        public long ID_Courses { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual Students Students { get; set; }
    }
}
